spring:
  application:
    name: user-service
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/ticketing
    username: math
    password: Pp11223344-
    driver-class-name: org.postgresql.Driver
server:
  port: 9090

